use clap::{App, Arg, SubCommand};

pub fn build_cli() -> App<'static, 'static> {
    App::new(env!("CARGO_PKG_NAME"))
            .about("An advanced file similarity analysis tool")
            .version(env!("CARGO_PKG_VERSION"))
            .subcommand(SubCommand::with_name("bash-completions")
                .about("Prints command completions for the Bash shell"))
            .subcommand(SubCommand::with_name("score")
                .about("Computes a similarity score between two files")
                .arg(Arg::with_name("file1")
                    .help("The first file to compare")
                    .required(true)
                    .index(1))
                .arg(Arg::with_name("file2")
                    .help("The second file to compare")
                    .required(true)
                    .index(2)))
            .subcommand(SubCommand::with_name("multiscore")
                .about("Computes similarity scores between multiple files")
                .arg(Arg::with_name("file_list1")
                    .help("Required. The first list of files to compare.")
                    .required(true))
                .arg(Arg::with_name("file_list2")
                    .help("Optional. The second list of files to compare. See below for more details.")
                    .required(false))
                .arg(Arg::with_name("mem")
                    .help("Pre-loads all files in memory. Faster but consumes more memory.")
                    .long("mem")
                    .takes_value(false)
                    .conflicts_with("no-mem"))
                .arg(Arg::with_name("no-mem")
                    .help("Loads files from disk on-demand. Slower but consumes less memory.")
                    .long("no-mem")
                    .takes_value(false)
                    .conflicts_with("mem"))
                .after_help("If one file list is provided, scores will be calculated among all unique file pairs in the list. If two file lists are provided, scores will be calculated among all file pairs between the two lists."))
}